version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./:/app
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
    php-fpm:
        image: php:8-fpm
        volumes:
            - ./:/app
    composer:
        image: composer:2.0
        volumes:
            - ./:/app
        command: ["composer", "install"]
    