version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./:/app
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
    php-fpm:
        image: php:8-fpm
        volumes:
            - ./:/app
    # php-cli:
    #     container_name: php-cli
    #     build:
    #         dockerfile: ./Dockerfile
    #     volumes:
    #         - ./:/var/www/html

    composer:
        image: composer:2.0
        volumes:
            # - ./docker-compose.yml:/var/www/html/docker-compose.yml
            - ./:/app
        command: ["composer", "install"]
    